os: linux
sudo: false
dist: trusty
language: php
matrix:
  include:
    - dist: precise
      php: 5.3
    - php: 7.1
    - php: 5.6
    - php: hhvm

install: composer install
script: vendor/bin/phpunit tests

